### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'range' and 'list'

### ISSUE THREAD

**Issue by openedev** [FlyingCatAlex/python-v4l2#5]
Running python-v4l2 on [v4l2.py](https://github.com/AlexJinlei/python-v4l2/blob/master/v4l2.py#L209) at target issuing below error, any proper fix?

Traceback (most recent call last):
  File "test_imports/test_misc.py", line 14, in <module>
    import v4l2
  File "usr/lib/python3.7/site-packages/v4l2.py", line 209, in <module>
TypeError: unsupported operand type(s) for +: 'range' and 'list'

**Comment by dj-foxxy** [comment]
Hi, edit the file and wrap the `range(...)` in a `list()`, e.g., `list(range(3, 4))`. Same issue on line 294.

**Comment by RustyRaptor** [comment]
Ok but when is this going to actually be fixed for real?

**Comment by Fkawala** [comment]
According to https://bugs.launchpad.net/python-v4l2/+bug/1664158 this bug is almost 2 years old, that's sad.

**Comment by aspotton** [comment]
If you're still seeing this problem, check out this repo which fixes it and supports Python 3.x: https://github.com/aspotton/python3-v4l2
